// Movies
export const GET_ALL_MOVIES_REQUEST = 'movie/GET_ALL_MOVIES_REQUEST';
export const GET_ALL_MOVIES_SUCCESS = 'movie/GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAILURE = 'movie/GET_ALL_MOVIES_FAILURE';

export const GET_MOVIES_REQUEST = 'movie/GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'movie/GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'movie/GET_MOVIES_FAILURE';

export const SELECTED_MOVIE_REQUEST = 'movie/SELECTED_MOVIE_REQUEST';
export const SELECTED_MOVIE_SUCCESS = 'movie/SELECTED_MOVIE_SUCCESS';
export const SELECTED_MOVIE_FAILURE = 'movie/SELECTED_MOVIE_FAILURE';

export const ADD_FAVORITE_REQUEST = 'movie/ADD_FAVORITE_REQUEST';
export const ADD_FAVORITE_SUCCESS = 'movie/ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAILURE = 'movie/ADD_FAVORITE_FAILURE';

export const REMOVE_FAVORITE_REQUEST = 'movie/REMOVE_FAVORITE_REQUEST';
export const REMOVE_FAVORITE_SUCCESS = 'movie/REMOVE_FAVORITE_SUCCESS';
export const REMOVE_FAVORITE_FAILURE = 'movie/REMOVE_FAVORITE_FAILURE';
