require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'IMDB' do
  # config = use_native_modules!

  # use_react_native!(:path => config["reactNativePath"])

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)

  # target 'IMDBTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  use_flipper!({ 'Flipper' => '0.122.0', 'Flipper-Folly' => '2.6.9', 'Flipper-RSocket' => '1.4.3', 'Flipper-DoubleConversion' => '3.1.7', 'Flipper-Glog' => '0.3.9', 'Flipper-PeerTalk' => '0.0.4' })


  

  

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  #     end
  #   end
  # end

  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  # use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      end
    end
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'IMDB-tvOS' do
  # Pods for IMDB-tvOS

  target 'IMDB-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
